"""Shared SSH/SCP helpers for Chorus evaluation scripts.

All remote operations go through plain ssh/scp so there is no dependency
on any cloud provider CLI.  Connection details are read from
``vm_config.json`` at the repo root (generated by ``configure_vms.py``).
"""

import json
import shlex
import subprocess
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
VM_CONFIG_PATH = REPO_DIR / "vm_config.json"


def load_vm_config() -> dict:
    """Load vm_config.json, or exit with a helpful message."""
    if not VM_CONFIG_PATH.exists():
        sys.exit(
            f"vm_config.json not found at {VM_CONFIG_PATH}.\n"
            "Run  python3 scripts/configure_vms.py  first to set up "
            "the compute VM connection."
        )
    try:
        return json.loads(VM_CONFIG_PATH.read_text())
    except (json.JSONDecodeError, OSError) as e:
        sys.exit(f"Error reading {VM_CONFIG_PATH}: {e}")


def _ssh_base(cfg: dict) -> list[str]:
    """Base ssh command fragment with key + options."""
    cmd = ["ssh"]
    if cfg.get("key"):
        cmd += ["-i", cfg["key"]]
    cmd += [
        "-o", "StrictHostKeyChecking=no",
        "-o", "UserKnownHostsFile=/dev/null",
        "-o", "LogLevel=ERROR",
    ]
    return cmd


def _scp_base(cfg: dict) -> list[str]:
    """Base scp command fragment with key + options."""
    cmd = ["scp"]
    if cfg.get("key"):
        cmd += ["-i", cfg["key"]]
    cmd += [
        "-o", "StrictHostKeyChecking=no",
        "-o", "UserKnownHostsFile=/dev/null",
        "-o", "LogLevel=ERROR",
    ]
    return cmd


def _target(cfg: dict) -> str:
    """user@host string."""
    return f"{cfg['user']}@{cfg['host']}"


def ssh_cmd(cfg: dict, command: str, *, check=True, capture=False):
    """Run *command* on the remote host via SSH."""
    cmd = _ssh_base(cfg) + [_target(cfg), f"bash -lc {shlex.quote(command)}"]
    print(f"    $ ssh {cfg['host']}: {command}")
    if capture:
        r = subprocess.run(cmd, capture_output=True, text=True)
        if check and r.returncode != 0:
            print(r.stderr, file=sys.stderr)
            if check:
                sys.exit(r.returncode)
        return r
    return subprocess.run(cmd, check=check)


def ssh_cmd_raw(cfg: dict, command: str, *, check=True, capture=False):
    """Like ssh_cmd but does NOT wrap in ``bash -lc``."""
    cmd = _ssh_base(cfg) + [_target(cfg), command]
    if capture:
        return subprocess.run(cmd, capture_output=True, text=True)
    return subprocess.run(cmd, check=check)


def scp_to(cfg: dict, local_path: str, remote_path: str):
    """Copy a file from the local machine to the remote host."""
    cmd = _scp_base(cfg) + [str(local_path), f"{_target(cfg)}:{remote_path}"]
    print(f"    $ scp → {cfg['host']}:{remote_path}")
    subprocess.run(cmd, check=True)


def scp_from(cfg: dict, remote_path: str, local_path: str):
    """Copy a file from the remote host to the local machine."""
    cmd = _scp_base(cfg) + [f"{_target(cfg)}:{remote_path}", str(local_path)]
    print(f"    $ scp ← {cfg['host']}:{remote_path}")
    subprocess.run(cmd, check=True)


def wait_for_ssh(cfg: dict, retries: int = 30, delay: int = 10):
    """Block until the remote host accepts SSH connections."""
    print(f"\n    Waiting for {cfg['host']} to accept SSH connections...")
    for i in range(retries):
        r = ssh_cmd_raw(cfg, "echo ok", check=False, capture=True)
        if r.returncode == 0:
            print("    SSH is ready.")
            return
        print(f"    Attempt {i + 1}/{retries} — not ready yet, retrying in {delay}s...")
        import time
        time.sleep(delay)
    sys.exit(f"    Timed out waiting for SSH on {cfg['host']}.")


def get_remote_interface(cfg: dict) -> str:
    """Get the default network interface on the remote host."""
    r = ssh_cmd_raw(
        cfg,
        "ip -o -4 route show to default | head -1 | cut -d' ' -f5",
        capture=True,
    )
    return r.stdout.strip() or "ens4"
